// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"mimokocke/internal/shared/permissions"
	"uuid"
)

type Authentication struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Provider     string
	ProviderID   *string
	PasswordHash *string
	CreatedAt    time.Time
	UpdatedAt    *time.Time
}

type Channel struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Provider       ChannelProvider
	Name           string
	Credentials    string
	Status         ChannelStatus
	CreatedAt      time.Time
	UpdatedAt      *time.Time
}

type Invitation struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	InviterID      uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	Role           permissions.MembershipRole
	Permissions    []permissions.MembershipPermission
	TokenHash      string
	ExpiresAt      time.Time
	AcceptedAt     *time.Time
	DeclinedAt     *time.Time
	CanceledAt     *time.Time
	CanceledByID   *uuid.UUID
	CreatedAt      time.Time
}

type Membership struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	FirstName      string
	LastName       string
	Role           permissions.MembershipRole
	Permissions    []permissions.MembershipPermission
	Status         MembershipStatus
	CanceledAt     *time.Time
	CanceledByID   *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      *time.Time
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt *time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt time.Time
	UpdatedAt *time.Time
}
