// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type Authentication struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Provider     string
	ProviderID   pgtype.Text
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Invitation struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	InviterID      uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	Role           string
	Permissions    []string
	TokenHash      string
	ExpiresAt      pgtype.Timestamptz
	AcceptedAt     pgtype.Timestamptz
	DeclinedAt     pgtype.Timestamptz
	CanceledAt     pgtype.Timestamptz
	CanceledByID   pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type Membership struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	FirstName      string
	LastName       string
	Role           string
	Permissions    []string
	Status         string
	CanceledAt     pgtype.Timestamptz
	CanceledByID   pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
