services:
  db:
    image: postgres:17-alpine
    container_name: dummy_db
    restart: always
    environment:
      - POSTGRES_USER=dummy
      - POSTGRES_PASSWORD=dummy
      - POSTGRES_DB=dummy
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
